#
# Macro file to run simulation of alphas from 244Cm
#

/testem/det/setGasMat isobutane10torr
/testem/det/setWinThick 1.5 um

/gps/pos/type Plane
/gps/pos/shape Rectangle
/gps/pos/centre -20 0 0
/gps/direction 1 0 0
/gps/pos/halfx 2.475 cm
/gps/pos/halfy 2.475 cm
/gps/pos/rot1 0 0 1
/gps/particle ion
/gps/ion 2 4 2
/gps/ene/type Mono
/gps/energy  5.80477 MeV
# /gps/pos/rot1 1 0 0
# /gps/pos/rot2 0 1 0
# /gps/ang/maxphi 3.14159265359

/run/beamOn 100
